language: python

sudo: required

dist: trusty

services:
  - docker

env:
  - DOCKER_IMAGE=debian-sid
  - DOCKER_IMAGE=debian-jessie
  - DOCKER_IMAGE=ubuntu-xenial
  - DOCKER_IMAGE=ubuntu-yakkety
  - DOCKER_IMAGE=ubuntu-zesty

before_install:
  - .travis/prepare.sh

script:
  - .travis/run.sh
