language: generic
# in order not to use virtualenv

sudo: required

dist: bionic

services:
  - docker

env:
  global:
    - SALT_VER="" # use "" for latest stable, other options: "git 2019.2.2"
    - COMPOSE_VER="1.22.0"
    - KUBECTL_VER="v1.16.3"
    - PYGIT2_VER="1.0.3"
    - GH_URL="https://kiemlicz.github.io/ambassador/"
    - BUILD_DIR=".local"
    - CHART_BRANCH="gh-pages"
    - BASE_PUB_NAME="envoy"
    - K8S_API_ENABLED=true

jobs:
  allow_failures:
    - env:
        - DOCKER_IMAGE=fedora-31
      before_install: .travis/prepare.sh dry
      script: .travis/test.sh dry
  include:
    - stage: test
      name: "Test and publish"
      env:
        - DOCKER_IMAGE=debian-buster
      before_install: .travis/prepare.sh dry
      script: .travis/test.sh dry
      after_success: .travis/publish.sh docker
    - env:
        - DOCKER_IMAGE=ubuntu-bionic
      before_install: .travis/prepare.sh dry
      script: .travis/test.sh dry
      after_success: .travis/publish.sh docker
    - env:
        - DOCKER_IMAGE=fedora-31
      before_install: .travis/prepare.sh dry
      script: .travis/test.sh dry
    - stage: masterless
      name: "Masterless tests"
      before_install: .travis/prepare.sh masterless
      script: .travis/test.sh masterless
      env:
        - DOCKER_IMAGE=debian-buster
        - BASE_IMAGE_TAG=buster
        - SALTENV=base
        - CONTEXT=base
    - before_install: .travis/prepare.sh masterless
      script: .travis/test.sh masterless
      env:
        - DOCKER_IMAGE=debian-buster
        - BASE_IMAGE_TAG=buster
        - SALTENV=base
        - CONTEXT=gui
    - before_install: .travis/prepare.sh masterless
      script: .travis/test.sh masterless
      env:
        - DOCKER_IMAGE=debian-buster
        - BASE_IMAGE_TAG=buster
        - SALTENV=dev
        - CONTEXT=dev
    - before_install: .travis/prepare.sh masterless
      script: .travis/test.sh masterless
      env:
        - DOCKER_IMAGE=ubuntu-bionic
        - SALTENV=base
        - CONTEXT=base
    - before_install: .travis/prepare.sh masterless
      script: .travis/test.sh masterless
      env:
        - DOCKER_IMAGE=ubuntu-bionic
        - SALTENV=dev
        - CONTEXT=dev
    - stage: k8s
      name: "Kubernetes tests"
      env:
        - DOCKER_IMAGE=debian-buster
        - SALTENV=server
        - CONTEXT=k8s
        - CHANGE_MINIKUBE_NONE_USER=true # adjusts minikube permissions when driver=none
      before_install: .travis/prepare.sh salt-master-run-k8s
      script: .travis/test.sh salt-master-run-k8s
      after_success: .travis/publish.sh chart
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: $BUILD_DIR
        target-branch: $CHART_BRANCH
        verbose: true
        on:
          branch: master
