language: python

sudo: required

dist: xenial

services:
  - docker

# don't add ubuntu non-LTSs versions
env:
  global:
    - SALT_VER="" # latest
    - CHANGE_MINIKUBE_NONE_USER=true # adjusts minikube permissions when driver=none
  matrix:
    - DOCKER_IMAGE=debian-sid
      TEST_CASE=salt-masterless-run
      SALTENV=base
      CONTEXT=base
    - DOCKER_IMAGE=debian-sid
      TEST_CASE=salt-masterless-run
      SALTENV=dev
      CONTEXT=dev
    - DOCKER_IMAGE=debian-stretch
      TEST_CASE=salt-masterless-run
      SALTENV=base
      CONTEXT=base
    - DOCKER_IMAGE=debian-stretch
      TEST_CASE=salt-masterless-run
      SALTENV=base
      CONTEXT=gui
    - DOCKER_IMAGE=debian-stretch
      TEST_CASE=salt-masterless-run
      SALTENV=dev
      CONTEXT=dev
    - DOCKER_IMAGE=ubuntu-bionic
      TEST_CASE=salt-masterless-run
      SALTENV=base
      CONTEXT=base
    - DOCKER_IMAGE=ubuntu-bionic
      TEST_CASE=salt-masterless-run
      SALTENV=dev
      CONTEXT=dev
    - DOCKER_IMAGE=debian-stretch
      TEST_CASE=salt-master-run-k8s
      SALTENV=dev
      CONTEXT=k8s
#    - DOCKER_IMAGE=debian-stretch
#      TEST_CASE=salt-master-run-compose
#      SALTENV=dev
#      CONTEXT=orch
#    - DOCKER_IMAGE=ubuntu-bionic
#      TEST_CASE=salt-master-run-compose
#      SALTENV=dev
#      CONTEXT=orch

matrix:
  fast_finish: true
  allow_failures: # only unstable distro-based tests are allowed to fail
    - env: DOCKER_IMAGE=debian-sid TEST_CASE=salt-masterless-run SALTENV=base CONTEXT=base
    - env: DOCKER_IMAGE=debian-sid TEST_CASE=salt-masterless-run SALTENV=dev CONTEXT=dev

before_install:
  - .travis/prepare.sh

script:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - .travis/test.sh
  - kill %1
  - .travis/after.sh

after_failure:
  - .travis/publish.sh
