language: python

sudo: required

dist: trusty

services:
  - docker

# don't add ubuntu non-LTSs versions
env:
  - DOCKER_IMAGE=debian-sid
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=debian-sid
    TEST_CASE=salt-masterless-run
    SALTENV=base
  - DOCKER_IMAGE=debian-sid
    TEST_CASE=salt-masterless-run
    SALTENV=gui
  - DOCKER_IMAGE=debian-sid
    TEST_CASE=salt-masterless-run
    SALTENV=dev
  - DOCKER_IMAGE=debian-jessie
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=debian-stretch
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=debian-stretch
    TEST_CASE=salt-masterless-run
    SALTENV=base
  - DOCKER_IMAGE=debian-stretch
    TEST_CASE=salt-masterless-run
    SALTENV=gui
  - DOCKER_IMAGE=debian-stretch
    TEST_CASE=salt-masterless-run
    SALTENV=dev
  - DOCKER_IMAGE=ubuntu-xenial
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=ubuntu-artful
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=debian-stretch
    TEST_FQDN=ambassadortest.com
    TEST_CASE=ambassador-run
  - DOCKER_IMAGE=debian-stretch
    TEST_CASE=salt-master-run

before_install:
  - .travis/prepare.sh

script:
  - travis_wait 60 .travis/run.sh
  - if [ "$TEST_CASE" == "salt-master-run" ]; then
      echo "scanning compose's containers"
      exit $(docker-compose -f .travis/"$DOCKER_IMAGE"/docker-compose.yml --project-directory=. ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v 0 | wc -l | tr -d ' '))
    fi

