language: generic
# in order not to use virtualenv

sudo: required

dist: bionic

services:
  - docker
  - redis

jobs:
  allow_failures:
    - env:
        - DOCKER_IMAGE=fedora-31
        - CONTEXT=syntax-test
        - TEST=syntax
      before_install: .travis/prepare.sh salt-test
      script: .travis/test.sh salt-test
  include:
    - stage: test
      name: "Test and publish"
      env:
        - DOCKER_IMAGE=debian-buster
        - CONTEXT=syntax-test
        - TEST=syntax
      before_install: .travis/prepare.sh salt-test
      script: .travis/test.sh salt-test
      after_success: .travis/publish.sh docker
    - env:
        - DOCKER_IMAGE=ubuntu-bionic
        - CONTEXT=syntax-test
        - TEST=syntax
      before_install: .travis/prepare.sh salt-test
      script: .travis/test.sh salt-test
      after_success: .travis/publish.sh docker
    - env:
        - DOCKER_IMAGE=fedora-31
        - CONTEXT=syntax-test
        - TEST=syntax
      before_install: .travis/prepare.sh salt-test
      script: .travis/test.sh salt-test
# todo it is possible to merge the stages however: how to run syntax tests first (in parallel) and then saltcheck using one runner only
    - stage: saltcheck
      name: "Saltcheck tests"
      before_install: .travis/prepare.sh salt-test
      script: .travis/test.sh salt-test
      env:
        - DOCKER_IMAGE=debian-buster
        - BASE_IMAGE_TAG=buster
        - SALTENV=server
        - CONTEXT=base
        - TEST=saltcheck
    - before_install: .travis/prepare.sh salt-test
      script: .travis/test.sh salt-test
      env:
        - DOCKER_IMAGE=debian-buster
        - BASE_IMAGE_TAG=buster
        - SALTENV=server
        - CONTEXT=server
        - TEST=saltcheck
    - before_install: .travis/prepare.sh salt-test
      script: .travis/test.sh salt-test
      env:
        - DOCKER_IMAGE=ubuntu-bionic
        - SALTENV=server
        - CONTEXT=base
        - TEST=saltcheck
    - before_install: .travis/prepare.sh salt-test
      script: .travis/test.sh salt-test
      env:
        - DOCKER_IMAGE=ubuntu-bionic
        - SALTENV=server
        - CONTEXT=server
        - TEST=saltcheck
    - stage: k8s
      name: "Kubernetes tests"
      env:
        - DOCKER_IMAGE=debian-buster
        - SALTENV=server
        - CONTEXT=k8s
        - CHANGE_MINIKUBE_NONE_USER=true # adjusts minikube permissions when driver=none
      before_install: .travis/prepare.sh salt-master-run-k8s
      script: .travis/test.sh salt-master-run-k8s
      after_success: .travis/publish.sh chart
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: $BUILD_DIR
        target-branch: $CHART_BRANCH
        verbose: true
        on:
          branch: master
