language: python

sudo: required

dist: trusty

services:
  - docker

# don't add ubuntu non-LTSs versions
env:
  global:
    - SALT_VER="" # latest
  matrix:
    - DOCKER_IMAGE=debian-sid
      TEST_CASE=salt-masterless-run
      SALTENV=base
      PILLARENV=base
    - DOCKER_IMAGE=debian-sid
      TEST_CASE=salt-masterless-run
      SALTENV=dev
      PILLARENV=dev
    - DOCKER_IMAGE=debian-stretch
      TEST_CASE=salt-masterless-run
      SALTENV=base
      PILLARENV=base
    - DOCKER_IMAGE=debian-stretch
      TEST_CASE=salt-masterless-run
      SALTENV=base
      PILLARENV=gui
    - DOCKER_IMAGE=debian-stretch
      TEST_CASE=salt-masterless-run
      SALTENV=dev
      PILLARENV=dev
    - DOCKER_IMAGE=ubuntu-bionic
      TEST_CASE=salt-masterless-run
      SALTENV=base
      PILLARENV=base
    - DOCKER_IMAGE=ubuntu-bionic
      TEST_CASE=salt-masterless-run
      SALTENV=dev
      PILLARENV=dev
    - DOCKER_IMAGE=debian-stretch
      TEST_FQDN=ambassadortest.com
      TEST_CASE=ambassador-run
    - DOCKER_IMAGE=debian-stretch
      TEST_CASE=salt-master-run
      SALTENV=dev
      PILLARENV=orch
# xenial cluster tests are disabled as salt-minion detects supervisord as systemd in docker and fails...
#    - DOCKER_IMAGE=ubuntu-xenial
#      TEST_CASE=salt-master-run
#      SALTENV=dev
#      PILLARENV=orch
    - DOCKER_IMAGE=ubuntu-bionic
      TEST_CASE=salt-master-run
      SALTENV=dev
      PILLARENV=orch

matrix:
  fast_finish: true
  allow_failures: # only unstable distro-based tests are allowed to fail
    - env: DOCKER_IMAGE=debian-sid TEST_CASE=salt-masterless-run SALTENV=base PILLARENV=base
    - env: DOCKER_IMAGE=debian-sid TEST_CASE=salt-masterless-run SALTENV=dev PILLARENV=dev

before_install:
  - .travis/prepare.sh

script:
  - travis_wait 60 .travis/run.sh
  - .travis/after.sh

after_failure:
  - .travis/publish.sh
