language: python

sudo: required

dist: trusty

services:
  - docker

env:
  - DOCKER_IMAGE=debian-sid
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=debian-sid
    TEST_CASE=salt-masterless-run
    SALTENV=base
  - DOCKER_IMAGE=debian-sid
    TEST_CASE=salt-masterless-run
    SALTENV=gui
  - DOCKER_IMAGE=debian-sid
    TEST_CASE=salt-masterless-run
    SALTENV=dev
  - DOCKER_IMAGE=debian-jessie
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=debian-stretch
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=debian-stretch
    TEST_CASE=salt-masterless-run
    SALTENV=base
  - DOCKER_IMAGE=debian-stretch
    TEST_CASE=salt-masterless-run
    SALTENV=gui
  - DOCKER_IMAGE=debian-stretch
    TEST_CASE=salt-masterless-run
    SALTENV=dev
  - DOCKER_IMAGE=ubuntu-xenial
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=ubuntu-yakkety
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=ubuntu-zesty
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=ubuntu-artful
    TEST_CASE=salt-masterless-dry
  - DOCKER_IMAGE=ubuntu-xenial
    TEST_FQDN=ambassadortest.com
    TEST_CASE=ambassador-run

before_install:
  - .travis/prepare.sh

script:
  - travis_wait 30 .travis/run.sh
