version: '3'

services:
  foreman:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "3000:3000"
      - "67:67/udp"
      - "68:68/udp"
    links:
      - db
      - redis
    volumes: []
    depends_on:
      - postgress

  db:
    environment:
      - POSTGRES_USER=foreman
      - POSTGRES_PASSWORD=foreman
      - POSTGRES_DATABASE=foreman
      - PGDATA=/var/lib/postgresql/data/pgdata
    hostname: db.ambassador
    image: postgres:10
    ports:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5432 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  db:
