version: '3'

services:
  # db only since plugin management is not yet sorted out
  # https://community.theforeman.org/t/dockerfile-is-now-included-in-foreman-core/13987/18
  db:
    environment:
      - POSTGRES_USER=foreman
      - POSTGRES_PASSWORD=foreman
      - POSTGRES_DATABASE=foreman
      - PGDATA=/var/lib/postgresql/data/pgdata
    network_mode: host
    hostname: db.ambassador
    image: postgres:10
    ports:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5432 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
