FROM debian:sid
RUN apt-get update && apt-get install -y curl
COPY envoy /srv/envoy
COPY .travis/entrypoint_run.sh /opt/
COPY .travis/minion.conf /etc/salt/minion.d/minion.conf
COPY .travis/pillar /srv/pillar
RUN ln -s /srv/envoy/salt /srv/salt
RUN curl -L https://bootstrap.saltstack.com | sh
ARG LOG_LEVEL
ENV LOG_LEVEL=$LOG_LEVEL

ENTRYPOINT ["/opt/entrypoint_run.sh", "$LOG_LEVEL"]
