# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define ENV['NAME'] do |instance|
        instance.vm.box = "debian/stretch64"
        instance.vm.hostname = ENV['NAME']
        instance.vm.provider :libvirt do |kvm|
            kvm.cpus = 2
            kvm.memory = 4096
            kvm.cputopology :sockets => '1', :cores => '2', :threads => '1'
        end
    end
    config.vm.provision "init", type: "shell" do |s|
        s.inline = <<-SHELL
            apt-get update
            apt-get install -y curl vim
            curl -L https://bootstrap.saltstack.com | sh
        SHELL
    end
end
