nameOverride: ""
fullnameOverride: "salt-provisioning"

saltMaster:
  replicaCount: 1

  image:
    tag: latest
    repository: "salt-master"
    pullPolicy: Never

  service:
    name: salt-master

saltMinion:
  image:
    tag: latest
    repository: "salt-minion"
    pullPolicy: Never

  service:
    name: salt-minion

storage:
  enabled: false
  createClass: false
  className: "local"

registry:
  enabled: false

persistence:
  enabled: true
  saltpkiSelector:
    matchLabels:
      name: salt-provisioning-salt-provisioning-saltpki
  saltqueueSelector:
    matchLabels:
      name: salt-provisioning-salt-provisioning-saltqueue

volume:
  enabled: true
  reclaimPolicy: Retain
  pki: "/mnt/data/saltpki"
  queue: "/mnt/data/saltqueue"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

logstash:
  fullnameOverride: "logstash"
  livenessProbe:
    httpGet:
      path: /
      port: monitor
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 60
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /
      port: monitor
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 60
    failureThreshold: 6
    successThreshold: 1
  persistence:
    enabled: false
  service:
    ports:
      syslog-udp:
        port: 1514
        targetPort: syslog-udp
        protocol: UDP
      beats:
        port: 5044
        targetPort: beats
        protocol: TCP
  ports:
    - name: syslog-udp
      containerPort: 1514
      protocol: UDP
    - name: beats
      containerPort: 5044
      protocol: TCP
  inputs:
    main: |-
      input {
        udp {
          port => 1514
          codec => json
        }
      }

  outputs:
    main: |-
      output {
        stdout { }
      }
