nameOverride: ""
fullnameOverride: "salt-provisioning"
namespace: "salt-provisioning"

saltMaster:
  replicaCount: 1

  image:
    tag: latest
    repository: "salt-master"
    pullPolicy: Never

  service:
    name: salt-master

saltMinion:
  image:
    tag: latest
    repository: "salt-minion"
    pullPolicy: Never

  service:
    name: salt-minion

storage:
  enable: true
  reclaimPolicy: Retain
  className: "local"

registry:
  enable: false

persistence:
  enable: true

volume:
  enable: true
  pki: "/mnt/data/saltpki"
  queue: "/mnt/data/saltqueue"
  affinity:
    hostnames:
      - minikube
