nameOverride: ""
fullnameOverride: "salt-provisioning"

logging:
  image:
    repository: "fluent/fluentd-kubernetes-daemonset"
    tag: "v1.3-debian-syslog"
  service:
    name: "fluentd"
    aggregatorName: "rsyslog"

saltMaster:
  replicaCount: 1

  image:
    tag: latest
    repository: "salt_master"
    pullPolicy: Never

  service:
    name: salt-master

saltMinion:
  image:
    tag: latest
    repository: "salt_minion"
    pullPolicy: Never

  service:
    name: salt-minion

storageClassName: "local"

registry:
  enable: false

volume:
  enable: true
  pki: "/mnt/data/saltpki"
  affinity:
    hostnames:
      - minikube
