{{- $root := . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.saltMinion.service.name }}
  labels:
    app: {{ .Values.saltMinion.service.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.saltMinion.service.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.saltMinion.service.name }}
    spec:
      serviceAccount: {{ include "salt.fullname" . }}
      serviceAccountName: {{ include "salt.fullname" . }}
      {{- if .Values.registry.enabled }}
      imagePullSecrets:
        - name: {{ include "salt.fullname" . }}-registry-credentials
      {{- end }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Values.saltMinion.service.name }}
          image: {{ .Values.saltMinion.image.repository }}:{{ tpl .Values.saltMinion.image.tag . }}
          imagePullPolicy: {{ .Values.saltMinion.image.pullPolicy }}
          readinessProbe: {{ .Values.saltMinion.readinessProbe | toYaml | nindent 12 }}
          livenessProbe: {{ .Values.saltMinion.livenessProbe | toYaml | nindent 12 }}
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
{{- range $key, $val := .Values.saltMinion.config }}
            - name: minion-config-{{ $key | replace "." "-" }}
              mountPath: /etc/salt/minion.d/{{ $key }}
              subPath: {{ $key }}
{{- end }}
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
{{- range $key, $val := .Values.saltMinion.config }}
        - name: minion-config-{{ $key | replace "." "-" }}
          configMap:
            name: {{ $root.Values.saltMinion.service.name }}-{{ $key | replace "." "-" }}-config-cm
            defaultMode: 0644
{{- end }}
