{{- $root := . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.saltMinion.service.name }}
  labels:
    {{- include "salt.labels" . | nindent 4 }}
    app: salt
    role: minion
spec:
  selector:
    matchLabels:
      app: salt
      role: minion
  template:
    metadata:
      labels:
        app: salt
        role: minion
        name: {{ .Values.saltMinion.service.name }}
    spec:
      serviceAccount: {{ include "salt.serviceAccountName" . }}
      serviceAccountName: {{ include "salt.serviceAccountName" . }}
{{- if .Values.registry.enabled }}
      imagePullSecrets:
        - name: {{ include "salt.fullname" . }}-registry-credentials
{{- end }}
      nodeSelector: {{ .Values.saltMinion.nodeSelector | toYaml | nindent 8 }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Values.saltMinion.service.name }}
          image: {{ .Values.saltMinion.image.repository }}:{{ tpl .Values.saltMinion.image.tag . }}
          imagePullPolicy: {{ .Values.saltMinion.image.pullPolicy }}
          env: {{ .Values.saltMinion.env | toYaml | nindent 12 }}
          resources: {{ .Values.saltMinion.resources | toYaml | nindent 12 }}
          readinessProbe: {{ .Values.saltMinion.readinessProbe | toYaml | nindent 12 }}
          livenessProbe: {{ .Values.saltMinion.livenessProbe | toYaml | nindent 12 }}
{{- if semverCompare "1.16.0" .Capabilities.KubeVersion.Version }}
          startupProbe: {{ .Values.saltMinion.startupProbe | toYaml | nindent 12 }}
{{- end }}
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
{{- range $key, $val := .Values.saltMinion.config }}
            - name: minion-config-{{ $key | replace "." "-" }}
              mountPath: /etc/salt/minion.d/{{ $key }}
              subPath: {{ $key }}
{{- end }}
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
{{- range $key, $val := .Values.saltMinion.config }}
        - name: minion-config-{{ $key | replace "." "-" }}
          configMap:
            name: {{ $root.Values.saltMinion.service.name }}-{{ $key | replace "." "-" }}-config-cm
            defaultMode: 0644
{{- end }}
