{{- $root := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.saltMaster.service.name }}
  labels:
    app.kubernetes.io/name: {{ include "salt.name" . }}
    helm.sh/chart: {{ include "salt.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ .Values.saltMaster.service.name }}
spec:
  replicas: {{ .Values.saltMaster.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.saltMaster.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.saltMaster.service.name }}
        name: {{ .Values.saltMaster.service.name }}
    spec:
      serviceAccount: {{ include "salt.fullname" . }}
      serviceAccountName: {{ include "salt.fullname" . }}
{{- if .Values.registry.enabled }}
      imagePullSecrets:
        - name: {{ include "salt.fullname" . }}-registry-credentials
{{- end }}
      volumes:
{{- range $key, $val := .Values.saltMaster.config }}
        - name: master-config-{{ $key | replace "." "-" }}
          configMap:
            name: {{ $root.Values.saltMaster.service.name }}-{{ $key | replace "." "-" }}-config-cm
            defaultMode: 0644
{{- end }}
        - name: pillar-overrides
          configMap:
            name: {{ .Values.saltMaster.service.name }}-pillar-overrides
            defaultMode: 0644
        - name: cloud-providers
          configMap:
            name: {{ .Values.saltMaster.service.name }}-cloud-providers-cm
            defaultMode: 0644
{{ if .Values.persistence.enabled }}
        - name: saltqueue
          persistentVolumeClaim:
            claimName: {{ include "salt.fullname" . }}-saltqueue
        - name: saltpki
          persistentVolumeClaim:
            claimName: {{ include "salt.fullname" . }}-saltpki
{{- else }}
        - name: saltqueue
          emptyDir: {}
        - name: saltpki
          emptyDir: {}
{{- end }}
      containers:
        - name: {{ .Values.saltMaster.service.name }}
          image: {{ .Values.saltMaster.image.repository }}:{{ tpl .Values.saltMaster.image.tag . }}
          imagePullPolicy: {{ .Values.saltMaster.image.pullPolicy }}
          readinessProbe: {{ .Values.saltMaster.readinessProbe | toYaml | nindent 12 }}
          livenessProbe: {{ .Values.saltMaster.livenessProbe | toYaml | nindent 12 }}
          ports:
            - name: publisher
              containerPort: 4505
            - name: reqserver
              containerPort: 4506
          volumeMounts:
            - mountPath: /etc/salt/pki/master
              name: saltpki
              readOnly: false
            - mountPath: /var/cache/salt/master/queues
              name: saltqueue
              readOnly: false
            - mountPath: /etc/salt/cloud.providers.d
              name: cloud-providers
              readOnly: false
            - mountPath: /srv/pillar/overrides
              name: pillar-overrides
              readOnly: true
{{- range $key, $val := .Values.saltMaster.config }}
            - name: master-config-{{ $key | replace "." "-" }}
              mountPath: /etc/salt/master.d/{{ $key }}
              subPath: {{ $key }}
              readOnly: false
{{- end }}
