{{ if .Values.volume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "salt.fullname" . }}-{{ .Release.Namespace }}-saltpki
  labels:
    name: {{ include "salt.fullname" . }}-{{ .Release.Namespace }}-saltpki
    role: saltpki
spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.volume.reclaimPolicy }}
{{ if .Values.storage.enabled }}
  storageClassName: {{ .Values.storage.className }}
{{ end }}
  local:
    path: {{ .Values.volume.pki }}
  nodeAffinity: {{ .Values.volume.nodeAffinity | toYaml | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "salt.fullname" . }}-{{ .Release.Namespace }}-saltqueue
  labels:
    name: {{ include "salt.fullname" . }}-{{ .Release.Namespace }}-saltqueue
    role: saltqueue
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.volume.reclaimPolicy }}
{{ if .Values.storage.enabled }}
  storageClassName: {{ .Values.storage.className }}
{{ end }}
  local:
    path: {{ .Values.volume.queue }}
  nodeAffinity: {{ .Values.volume.nodeAffinity | toYaml | nindent 4 }}
{{- end }}
