{{ if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "salt.fullname" . }}-saltpki
spec:
{{ if .Values.storage.enabled }}
  storageClassName: {{ .Values.storage.className }}
{{ end }}
{{ if .Values.persistence.saltPkiSelector }}
  selector: {{ .Values.persistence.saltPkiSelector | toYaml | nindent 4 }}
{{ end }}
  accessModes:
    - ReadWriteOnce
  resources: {{ .Values.persistence.saltPkiResources | toYaml | nindent 4 }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "salt.fullname" . }}-saltqueue
spec:
{{ if .Values.storage.enabled }}
  storageClassName: {{ .Values.storage.className }}
{{ end }}
{{ if .Values.persistence.saltQueueSelector }}
  selector: {{ .Values.persistence.saltQueueSelector | toYaml | nindent 4 }}
{{ end }}
  accessModes:
    - ReadWriteOnce
  resources: {{ .Values.persistence.saltQueueResources | toYaml | nindent 4 }}
{{- end }}
