{{- $root := . -}}
{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "salt.fullname" . }}-registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.saltMaster.service.name }}-apicerts
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
{{- range $key, $val := .Values.saltMaster.apicerts }}
  {{ $key }}: {{ tpl $val $root | toYaml | nindent 4 }}
{{- end }}
