version: '3.4'
services:
  master:
    build:
      context: .
      dockerfile: .travis/debian-stretch/master/Dockerfile
      args:
        - LOG_LEVEL
        - SALTENV=dev
    hostname: master
    domainname: public.com
    ports:
     - "4505:4505"
     - "4506:4506"
    links:
      - minion1
      - minion2
      - minion3
  minion1:
    build:
      context: .
      dockerfile: .travis/debian-stretch/minion/Dockerfile
    hostname: minion1
    domainname: public.com
  minion2:
    build:
      context: .
      dockerfile: .travis/debian-stretch/minion/Dockerfile
    hostname: minion2
    domainname: public.com
  minion3:
    build:
      context: .
      dockerfile: .travis/debian-stretch/minion/Dockerfile
    hostname: minion3
    domainname: public.com
