version: '3.4'
services:
  master:
    image: salt_master
    build:
      context: .
      dockerfile: .travis/debian-stretch/master/Dockerfile
      args:
        hostname: master.local
        saltenv: $SALTENV
        pillarenv: $PILLARENV
        salt_ver: $SALT_VER
        log_level: $LOG_LEVEL
    hostname: master
    domainname: local
    privileged: true
    ports:
     - "4505:4505"
     - "4506:4506"
    networks:
      local:
        aliases:
          - master.local
#      hostnet: {}
  minion1:
    image: salt_minion
    build:
      context: .
      dockerfile: .travis/debian-stretch/minion/Dockerfile
      args:
        hostname: minion1.local
        salt_ver: $SALT_VER
    hostname: minion1
    domainname: local
    privileged: true
    depends_on:
      - master
    networks:
      local:
        aliases:
          - minion1.local
  minion2:
    image: salt_minion
    build:
      context: .
      dockerfile: .travis/debian-stretch/minion/Dockerfile
      args:
        hostname: minion2.local
        salt_ver: $SALT_VER
    hostname: minion2
    domainname: local
    privileged: true
    depends_on:
      - master
    networks:
      local:
        aliases:
          - minion2.local
  minion3:
    image: salt_minion
    build:
      context: .
      dockerfile: .travis/debian-stretch/minion/Dockerfile
      args:
        hostname: minion3.local
        salt_ver: $SALT_VER
    hostname: minion3
    domainname: local
    privileged: true
    depends_on:
      - master
    networks:
      local:
        aliases:
          - minion3.local

networks:
  local:
    driver: bridge
#  hostnet:
#    external:
#      name: host
