FROM debian:stretch
RUN apt-get update && apt-get install -y curl python-pip
COPY envoy /srv/envoy
COPY .travis/entrypoint_run.sh /opt/
COPY .travis/minion.conf /etc/salt/minion.d/minion.conf
COPY .travis/pillar /srv/pillar
RUN ln -s /srv/envoy/salt /srv/salt
RUN curl -L https://bootstrap.saltstack.com | sh
RUN pip install --upgrade google-auth
ARG LOG_LEVEL
ARG SALTENV

ENTRYPOINT /opt/entrypoint_run.sh $SALTENV $LOG_LEVEL
