version: '3.4'
services:
  master:
    image: salt_master
    build:
      context: .
      dockerfile: .travis/debian-stretch/master/Dockerfile
      args:
        - HOSTNAME=master
        - SALTENV=dev
        - LOG_LEVEL
    hostname: master
    domainname: local
    privileged: true
    ports:
     - "4505:4505"
     - "4506:4506"
    links:
      - minion1
      - minion2
      - minion3
  minion1:
    image: salt_minion
    build:
      context: .
      dockerfile: .travis/debian-stretch/minion/Dockerfile
    hostname: minion1
    domainname: local
    privileged: true
  minion2:
    image: salt_minion
    build:
      context: .
      dockerfile: .travis/debian-stretch/minion/Dockerfile
    hostname: minion2
    domainname: local
    privileged: true
  minion3:
    image: salt_minion
    build:
      context: .
      dockerfile: .travis/debian-stretch/minion/Dockerfile
    hostname: minion3
    domainname: local
    privileged: true
