nameOverride: "salt"
fullnameOverride: ""

serviceAccount:
  create: true

saltMaster:
  replicaCount: 1

  image:
    repository: "envoy-master-debian-stretch"
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    name: salt-master
    annotations: {}

  # /etc/salt/master.d/ config files, must end with .conf suffix
  config: {}

  cloudProviders: {}

  pillar: {}

  # the reactor sls files
  reactor: {}

  readinessProbe:
    tcpSocket:
      port: publisher
    initialDelaySeconds: 15
    periodSeconds: 20

  livenessProbe:
    tcpSocket:
      port: publisher
    initialDelaySeconds: 60
    periodSeconds: 40

saltMinion:
  image:
    repository: "envoy-minion-debian-stretch"
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    name: salt-minion

  config: {}

  readinessProbe:
    exec:
      command:
        - salt-call
        - --local
        - test.ping
    initialDelaySeconds: 60
    periodSeconds: 30

  livenessProbe:
    exec:
      command:
        - salt-call
        - --local
        - test.ping
    initialDelaySeconds: 120
    periodSeconds: 60

storage:
  enabled: false
  createClass: false
  className: "local"

registry:
  enabled: false

persistence:
  enabled: true
  saltPkiResources:
    requests:
      storage: 5Mi
  saltPkiSelector: {}
  saltQueueResources:
    requests:
      storage: 128Mi
  saltQueueSelector: {}

volume:
  enabled: false
  reclaimPolicy: Retain
  pki: "/mnt/data/saltpki"
  queue: "/mnt/data/saltqueue"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

logstash:
  enabled: false
  livenessProbe:
    httpGet:
      path: /
      port: monitor
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 60
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /
      port: monitor
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 60
    failureThreshold: 6
    successThreshold: 1
  service:
    ports:
      syslog-udp:
        port: 1514
        targetPort: syslog-udp
        protocol: UDP
      beats:
        port: 5044
        targetPort: beats
        protocol: TCP
  ports:
    - name: syslog-udp
      containerPort: 1514
      protocol: UDP
    - name: beats
      containerPort: 5044
      protocol: TCP
