nameOverride: "salt"
fullnameOverride: ""

serviceAccount:
  create: true

saltMaster:
  replicaCount: 1

  image:
    repository: "envoy-master-debian-buster"
    tag: '{{ default "latest" .Chart.AppVersion }}'
    pullPolicy: IfNotPresent

  service:
    name: salt-master
    annotations: {}

  # /etc/salt/master.d/ config files, must end with .conf suffix
  config: {}

  cloudProviders: {}

  pillar: {}

  # the reactor sls files
  reactor: {}

  # the thorium state tree
  thorium: {}

  apicerts: {}

  # memory and cpu limits for salt-master, typically 4Gi is max
  resources: {}

  env: []

  readinessProbe:
    tcpSocket:
      port: pubsub
    initialDelaySeconds: 15
    periodSeconds: 20

  livenessProbe:
    tcpSocket:
      port: pubsub
    initialDelaySeconds: 45
    periodSeconds: 40

  startupProbe: {}

  # Deploy Salt Minion container to the Salt Master POD
  minion:
    enabled: false

saltMinion:
  image:
    repository: "envoy-minion-debian-buster"
    tag: '{{ default "latest" .Chart.AppVersion }}'
    pullPolicy: IfNotPresent

  service:
    name: salt-minion

  config: {}

  # memory and cpu limits for salt-master, typically 1Gi is max
  resources: {}

  env: []

  # not using --local in minion probes, may seem like a good idea, however:
  # - this way the probe succeeds only when established master communication
  # - master won't be able to reach not ready minion
  # still not sure if would be a good idea (master crash will cause minion restart as well)
  readinessProbe:
    exec:
      command:
        - salt-call
        - --local
        - test.ping
    initialDelaySeconds: 15
    periodSeconds: 20

  livenessProbe:
    exec:
      command:
        - salt-call
        - --local
        - test.ping
    initialDelaySeconds: 45
    periodSeconds: 40

  # typically when --local is used for readiness/liveness probe, the startup probe shouldn't be defined
  startupProbe: {}

  # pick nodes where Salt Minion should be deployed
  nodeSelector: {}

# alter the Salt capabilities, set roles that best suit the needs
clusterRole:
  create: true
  resources:
    - pods
    - namespaces
    - statefulsets
    - daemonsets
    - deployments
  verbs:
    - get
    - list
    - watch

storage:
  enabled: false
  createClass: false
  className: "local"

registry:
  enabled: false

persistence:
  enabled: true
  saltPkiResources:
    requests:
      storage: 5Mi
  saltPkiSelector: {}
  saltQueueResources:
    requests:
      storage: 128Mi
  saltQueueSelector: {}

volume:
  enabled: false
  reclaimPolicy: Retain
  pki: "/mnt/data/saltpki"
  queue: "/mnt/data/saltqueue"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

logstash:
  enabled: false
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 60
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 60
    failureThreshold: 6
    successThreshold: 1
  service:
    ports:
      - name: syslog-udp
        port: 1514
        protocol: UDP
      - name: beats
        port: 5044
        protocol: TCP
