nameOverride: ""
fullnameOverride: "salt-provisioning"

saltMaster:
  replicaCount: 1

  image:
    tag: "{{ .Chart.AppVersion }}"
    repository: "envoy-master-debian-stretch"
    pullPolicy: IfNotPresent

  service:
    name: salt-master

#  config:
#    custom.conf: |-
#      use_superseded:
#        - module.run
  config: {}

  cloudProviders: {}

  pillar: |-
    salt:
      kubernetes: {{ "{{" }} salt['sdb.get']("sdb://k8s/daemon_set?name={{ .Values.saltMinion.service.name }}") {{ "}}" }}

  readinessProbe:
    tcpSocket:
      port: publisher
    initialDelaySeconds: 15
    periodSeconds: 20

  livenessProbe:
    tcpSocket:
      port: publisher
    initialDelaySeconds: 60
    periodSeconds: 40

saltMinion:
  image:
    tag: "{{ .Chart.AppVersion }}"
    repository: "envoy-minion-debian-stretch"
    pullPolicy: IfNotPresent

  service:
    name: salt-minion

  config:
    custom.conf: |-
      use_superseded:
        - module.run

      #tests are run in docker
      #override provider because in docker container the default one could be impossible to use (e.g. systemd)
      providers:
        service: service

      auth_safemode: False
      ping_interval: 1
      rejected_retry: True

      engines:
        - docker_events:
            docker_url: unix://var/run/docker.sock
            filters:
              event:
                 - create
                 - start
                 - stop
                 - die
                 - oom

      master: "salt-master"

      mine_functions:
        network.interfaces: []
        network.ip_addrs: []

      logstash_udp_handler:
        host: logstash.logging
        port: 1514
        version: 1
        msg_type: logstash

      beacons:
        status:
          - interval: 45

  readinessProbe:
    exec:
      command:
        - cat
        - /tmp/salt/healthz
    initialDelaySeconds: 30
    periodSeconds: 10

  livenessProbe:
    exec:
      command:
        - cat
        - /tmp/salt/healthz
    initialDelaySeconds: 90
    periodSeconds: 15

storage:
  enabled: false
  createClass: false
  className: "local"

registry:
  enabled: false

persistence:
  enabled: true
  saltPkiResources:
    requests:
      storage: 5Mi
  saltPkiSelector:
    matchLabels:
      role: saltpki
  saltQueueResources:
    requests:
      storage: 128Mi
  saltQueueSelector:
    matchLabels:
      role: saltqueue

volume:
  enabled: false
  reclaimPolicy: Retain
  pki: "/mnt/data/saltpki"
  queue: "/mnt/data/saltqueue"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

logstash:
  fullnameOverride: "logstash"
  livenessProbe:
    httpGet:
      path: /
      port: monitor
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 60
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /
      port: monitor
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 60
    failureThreshold: 6
    successThreshold: 1
  persistence:
    enabled: false
  service:
    ports:
      syslog-udp:
        port: 1514
        targetPort: syslog-udp
        protocol: UDP
      beats:
        port: 5044
        targetPort: beats
        protocol: TCP
  ports:
    - name: syslog-udp
      containerPort: 1514
      protocol: UDP
    - name: beats
      containerPort: 5044
      protocol: TCP
  inputs:
    main: |-
      input {
        udp {
          port => 1514
          codec => json
        }
      }

  outputs:
    main: |-
      output {
        stdout { }
      }
