kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.saltMaster.service.name }}-pillar-cm
  namespace: {{ .Values.namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  init.sls: |-
    salt:
      kubernetes: {{ "{{" }} salt['sdb.get']("sdb://k8s/daemon_set?name={{ .Values.saltMinion.service.name }}") {{ "}}" }}
