{{ if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "salt.fullname" . }}-saltpki
spec:
{{ if .Values.storage.enabled }}
  storageClassName: {{ .Values.storage.className }}
{{ end }}
  selector: {{ .Values.persistence.saltpkiSelector | toYaml | nindent 4 }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "salt.fullname" . }}-saltqueue
spec:
{{ if .Values.storage.enabled }}
  storageClassName: {{ .Values.storage.className }}
{{ end }}
  selector: {{ .Values.persistence.saltqueueSelector | toYaml | nindent 4 }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
{{- end }}
