{{ if .Values.persistence.enable }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "salt.fullname" . }}-saltpki
spec:
  storageClassName: {{ .Values.storage.className }}
{{- if .Values.volume.enable }}
  selector:
    matchLabels:
      name: {{ include "salt.fullname" . }}-saltpki
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "salt.fullname" . }}-saltqueue
spec:
  storageClassName: {{ .Values.storage.className }}
{{- if .Values.volume.enable }}
  selector:
    matchLabels:
      name: {{ include "salt.fullname" . }}-saltqueue
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
{{- end }}
