{{- if .Values.registry.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "salt.fullname" . }}-registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
