kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.saltMaster.service.name }}
  namespace: {{ include "salt.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "salt.name" . }}
    helm.sh/chart: {{ include "salt.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Values.saltMaster.service.name }}
spec:
  selector:
    app: {{ .Values.saltMaster.service.name }}
  ports:
    - protocol: TCP
      name: pubsub
      port: 4505
      targetPort: 4505
    - protocol: TCP
      name: reqreply
      port: 4506
      targetPort: 4506
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.logging.service.aggregatorName }}
  namespace: {{ include "salt.fullname" . }}
spec:
  selector:
    app: {{ .Values.logging.service.aggregatorName }}
  ports:
    - name: tcp-syslog
      port: 514
      targetPort: 514
      protocol: TCP
    - name: udp-syslog
      port: 514
      targetPort: 514
      protocol: UDP
    - name: fluentd
      port: 24224
      targetPort: 24224
      protocol: TCP
