---
:enabled: https
:autosign_file: /etc/salt/autosign.conf
:salt_command_user: root
:use_api: true
:api_url: https://{{ salt['pillar.get']("foreman:fqdn") }}:{{ salt['pillar.get']("salt:api:port") }}
:api_auth: pam
:api_username: {{ salt['pillar.get']("salt:api:username") }}
:api_password: {{ salt['pillar.get']("salt:api:password") }}
