{% from "foreman/map.jinja" import foreman with context -%}
{% from "salt/map.jinja" import salt_installer with context -%}
---
:enabled: https
:autosign_file: {{ salt_installer.master.config|selectattr("name", "match", ".*autosign.conf.*")|first }}
:salt_command_user: root
:use_api: true
:api_url: https://{{ foreman.fqdn }}:{{ salt_installer.api.port }}
:api_auth: pam
:api_username: {{ salt_installer.api.username }}
:api_password: {{ salt_installer.api.password }}
