---
:proto: https
:host: %AMBASSADOR_FQDN%
:url: https://%AMBASSADOR_FQDN%
:port: 443
:ssl_ca: %AMBASSADOR_CA%
:ssl_cert: %AMBASSADOR_CERT%
:ssl_key: %AMBASSADOR_KEY%
:timeout: 10
:salt: /usr/bin/salt
:upload_grains: true
