version: '3.4'
services:
  master:
    image: salt_master
    build:
      context: .
      dockerfile: .travis/$DOCKER_IMAGE/Dockerfile
      taget: master-compose-test
      args:
        saltenv: $SALTENV
        log_level: $LOG_LEVEL
    hostname: salt-master
    domainname: local
    privileged: true
    ports:
     - "4505:4505"
     - "4506:4506"
    networks:
      local:
        aliases:
          - master.local
#      hostnet: {}
  minion1:
    image: salt_minion
    build:
      context: .
      dockerfile: .travis/$DOCKER_IMAGE/Dockerfile
      taget: minion-compose-test
    hostname: minion1
    domainname: local
    privileged: true
    depends_on:
      - master
    networks:
      local:
        aliases:
          - minion1.local
  minion2:
    image: salt_minion
    build:
      context: .
      dockerfile: .travis/$DOCKER_IMAGE/Dockerfile
      taget: minion-compose-test
    hostname: minion2
    domainname: local
    privileged: true
    depends_on:
      - master
    networks:
      local:
        aliases:
          - minion2.local
  minion3:
    image: salt_minion
    build:
      context: .
      dockerfile: .travis/$DOCKER_IMAGE/Dockerfile
      taget: minion-compose-test
    hostname: minion3
    domainname: local
    privileged: true
    depends_on:
      - master
    networks:
      local:
        aliases:
          - minion3.local

networks:
  local:
    driver: bridge
#  hostnet:
#    external:
#      name: host
