apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: salt
  namespace: provisioning
  labels:
    app: salt
spec:
  selector:
    matchLabels:
      name: salt
  template:
    metadata:
      labels:
        name: salt
    spec:
      containers:
        - name: salt-master
          image: salt_master:latest
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
