saltMaster:
  image:
    tag: latest
    repository: "salt-master"
    pullPolicy: Never
  # travis uses dedicated image
#  config:
#    custom.conf: |-

saltMinion:
  image:
    tag: latest
    repository: "salt-minion"
    pullPolicy: Never
  # travis uses dedicated image

volume:
  enabled: true
  reclaimPolicy: Retain
  pki: "/mnt/data/saltpki"
  queue: "/mnt/data/saltqueue"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
