saltMaster:
  image:
    tag: latest
    repository: "salt-master"
    pullPolicy: Never
  # travis uses dedicated image
  config:
    custom.conf: |-
      #autosign_file: /etc/salt/master.d/autosign
      #event_return: rawfile_json
      #rawfile_json.filename: /var/log/salt/events
      #log_level: debug
      #log_level_logfile: debug

      engines:
        - thorium: {}
        - k8s_events: {}

      # queue config
      runner_queue:
        queue: runner_queue
        backend: sqlite

      schedule:
        runner_queue:
          function: queue.process_runner
          minutes: 1
          kwargs:
            quantity: 1

      reactor:
        - 'salt/minion/*/start':
          - /srv/reactor/minion_ready.sls

      color: False
      log_fmt_console: '[%(levelname)-8s] %(message)s'
      log_fmt_logfile: '%(asctime)s,%(msecs)03d [%(name)-17s][%(levelname)-8s] %(message)s'
      logstash_udp_handler:
        host: logstash.salt-provisioning
        port: 1514
        version: 1
        msg_type: logstash

  pillar: |-
    salt:
      kubernetes: {{ "{{" }} salt['sdb.get']("sdb://k8s/daemon_set?name={{ .Values.saltMinion.service.name }}") {{ "}}" }}

saltMinion:
  image:
    tag: latest
    repository: "salt-minion"
    pullPolicy: Never

  config:
    custom.conf: |-
      master: "salt-master"

      mine_functions:
        network.interfaces: []
        network.ip_addrs: []

      beacons:
        status:
          - interval: 45

      color: False
      log_fmt_console: '[%(levelname)-8s] %(message)s'
      log_fmt_logfile: '%(asctime)s,%(msecs)03d [%(name)-17s][%(levelname)-8s] %(message)s'
      logstash_udp_handler:
        host: logstash.salt-provisioning
        port: 1514
        version: 1
        msg_type: logstash

persistence:
  saltPkiSelector:
      matchLabels:
        role: saltpki
  saltQueueSelector:
    matchLabels:
      role: saltqueue

volume:
  enabled: true
  reclaimPolicy: Retain
  pki: "/mnt/data/saltpki"
  queue: "/mnt/data/saltqueue"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

logstash:
  enabled: true
  fullnameOverride: "logstash"
  persistence:
    enabled: false
  inputs:
    main: |-
      input {
        udp {
          port => 1514
          codec => json
        }
      }
  filters:
    main: |-
      filter {
        mutate {
          remove_field => [ "bracketprocess", "type", "colorname", "@version", "exc_info_on_loglevel", "stack_info", "jid", "tags", "colorprocess", "colormsg", "bracketlevel", "bracketname", "colorlevel" ]
        }
      }
  outputs:
    main: |-
      output {
        stdout { }
      }