saltMaster:
  image:
    tag: latest
    repository: "salt-master"
    pullPolicy: Never
  # travis uses dedicated image
  config:
    master.conf: |-
      fileserver_backend:
        - roots

      file_roots:
        base:
          - /srv/salt/base
          - /srv/reactor
        dev:
          - /srv/salt/dev
          - /srv/salt/base
          - /srv/reactor
        server:
          - /srv/salt/server
          - /srv/salt/dev
          - /srv/salt/base
          - /srv/reactor

      autosign_file: /etc/salt/master.d/autosign.conf

      #dumps events to file for easier assertion of success/failure
      event_return: rawfile_json
      rawfile_json.filename: /var/log/salt/events

      log_level: info

      ext_pillar_first: True
      pillar_merge_lists: True
      pillar_opts: True

      use_superseded:
        - module.run

    custom.conf: |-
      #event_return: rawfile_json
      #rawfile_json.filename: /var/log/salt/events
      #log_level: debug
      #log_level_logfile: debug

      engines:
        - thorium: {}
        - k8s_events: {}

      # queue config
      runner_queue:
        queue: runner_queue
        backend: sqlite

      schedule:
        runner_queue:
          function: queue.process_runner
          minutes: 1
          kwargs:
            quantity: 1

      reactor:
        - 'salt/minion/*/start':
          - /srv/reactor/minion-ready.sls
        #- 'salt/engines/docker_events/*':
        #  - /srv/reactor/docker_events_reactor.sls

      color: False
      log_fmt_console: '[%(levelname)-8s] %(message)s'
      log_fmt_logfile: '%(asctime)s,%(msecs)03d [%(name)-17s][%(levelname)-8s] %(message)s'
      logstash_udp_handler:
        host: logstash.salt-provisioning
        port: 1514
        version: 1
        msg_type: logstash

    autosign.conf: |-
      minion1.local
      minion2.local
      minion3.local
      minion4.local
      minion5.local
      salt-*

  pillar:
    top.sls: |-
      base:
        '*':
          - kubernetes
    kubernetes.sls: |-
      salt:
        kubernetes: {{ "{{" }} salt['sdb.get']("sdb://k8s/daemon_set?name={{ .Values.saltMinion.service.name }}") {{ "}}" }}

  reactor:
    minion-ready.sls: |-
      {% if data['id'] is match('salt-minion-\S+') %}
      k8s_ready:
          local.state.sls:
              - tgt: {{ "{{" }} data['id'] {{ "}}" }}
              - args:
                - mods:
                  - minion
                - saltenv: {{ "{{" }} salt['environ.get']("SALTENV") {{ "}}" }}
                - pillar:
                      docker_event: {{ "{{" }} data|tojson {{ "}}" }}
      {% endif %}

saltMinion:
  image:
    tag: latest
    repository: "salt-minion"
    pullPolicy: Never

  config:
    custom.conf: |-
      master: "salt-master"

      mine_functions:
        network.interfaces: []
        network.ip_addrs: []

      beacons:
        status:
          - interval: 45

      color: False
      log_fmt_console: '[%(levelname)-8s] %(message)s'
      log_fmt_logfile: '%(asctime)s,%(msecs)03d [%(name)-17s][%(levelname)-8s] %(message)s'
      logstash_udp_handler:
        host: logstash.salt-provisioning
        port: 1514
        version: 1
        msg_type: logstash

persistence:
  saltPkiSelector:
      matchLabels:
        role: saltpki
  saltQueueSelector:
    matchLabels:
      role: saltqueue

volume:
  enabled: true
  reclaimPolicy: Retain
  pki: "/mnt/data/saltpki"
  queue: "/mnt/data/saltqueue"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

logstash:
  enabled: true
  fullnameOverride: "logstash"
  persistence:
    enabled: false
  inputs:
    main: |-
      input {
        udp {
          port => 1514
          codec => json
        }
      }
  filters:
    main: |-
      filter {
        mutate {
          remove_field => [ "bracketprocess", "type", "colorname", "@version", "exc_info_on_loglevel", "stack_info", "jid", "tags", "colorprocess", "colormsg", "bracketlevel", "bracketname", "colorlevel" ]
        }
      }
  outputs:
    main: |-
      output {
        stdout { }
      }