name: Ambassador test
on:
  - push

jobs:
  debug:
    name: "Podman debug"
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          echo "start"
          podman run --help
          echo "Building Podman image"
          sudo podman build -t debug:latest podman
          echo "Running podman container"
          sudo podman run --name debug_name --network=host --hostname bla --privileged --systemd=true "debug:latest"